### PR TITLE
all parameters on main class

### PR DESCRIPTION
**Pull request by SimonHoenscheid**
* move subclass parameters with defaults to main class
* lookup default in main class
* copy parameter documentation if available

### CODE REVIEW

**Comment by m0dular** [comment]
@SimonHoenscheid We have a couple of duplicate parameters that are tripping up the validfation.

```
pdk (ERROR): puppet-syntax: The parameter 'manage_reports_autovacuum_cost_delay' is declared more than once (the parameter list (file: /home/adrian/repos/puppetlabs-pe_databases/manifests/init.pp, line: 49, column: 14))
pdk (ERROR): puppet-syntax: The parameter 'factsets_autovacuum_vacuum_scale_factor' is declared more than once (the parameter list (file: /home/adrian/repos/puppetlabs-pe_databases/manifests/init.pp, line: 50, column: 24))
```

**Comment by SimonHoenscheid** [comment]
@m0dular I fixed these issues

**Comment by SimonHoenscheid** [comment]
@m0dular @MartyEwings please review again

**Comment by m0dular** [comment]
Hi, sorry about the delay on this one.  We have another PR #112 that should be merged soon that will be incompatible with this one.  We have postgres tuning related stuff in the product at this point, so the `postgresql_settings` classes in this module are mostly redundant.

It might not be well documented at this point, but the database profile class does some calculations to come up with the postgres settings, which should also be configurable if needed.  For example, `puppet_enterprise::profile::database::work_mem` for `work_mem`.

If there's anything in this PR that isn't related to the deprecated classes, could you rebase it onto #112?  Thanks.

**Comment by SimonHoenscheid** [comment]
I think it makes sense to close this for now.

**Pull request closed without merging**
