### PR TITLE
(maint) correct lint issues found on forge

### PR DESCRIPTION
**Pull request by tkishel**
hidden by .puppet-lint.rc

### CODE REVIEW

**Comment by tkishel** [comment]
All sin tax!

**Comment by jarretlavallee** [comment]
Can you remove the following from the `.sync.yaml` and do a `pdk update`? Right now the CI tests are skipping these checks as well.

https://github.com/puppetlabs/puppetlabs-pe_databases/blob/master/.sync.yml#L21-L24

**Comment by jarretlavallee** [comment]
The last commit is missing the update to the `Rakefile`. Did the `pdk update` modify it? pdk should have removed the following lines.

https://github.com/puppetlabs/puppetlabs-pe_databases/blob/master/Rakefile#L41-L43

**Comment by jarretlavallee** [comment]
Looks good. We just need to drop the 4.x testing in travis since we don't support it in the module any more. 

https://github.com/puppetlabs/puppetlabs-pe_databases/blob/master/.sync.yml#L26-L29

**Comment by tkishel** [comment]
So many layers to edit ... done.

**Pull request merged**
