### PR TITLE
CI Initial commit

### PR DESCRIPTION
**Pull request by m0dular**

### CODE REVIEW

**Comment by MartyEwings** [comment]
@m0dular The workflows wont run on first commit from a fork, I don't know whether we should commit to MAIN and resolve any issues post commit, or merge into a branch and check there first before promoting to MAIN, what do you think?

**Comment by MartyEwings** [comment]
as there are no existing github actions in the upstream repo this isn't running the workflows, we may neet to pull into a new branch and test there? alternatively we can merge to main and fix if there are any issue directly?

**Comment by m0dular** [comment]
Kicked off the tests with a dummy pr.

**Review by MartyEwings — APPROVED** [review]
@m0dular looks good to me now, Looks like the open ended Puppet Version was not something the test matrix script was expecting, I also think this is a metadata formatting issue that would flag in latest PDK anyway

**Pull request merged**
