### PR TITLE
Changes to pg_repack.pp and pg_repack_spec.rb per SUP-2405

### PR DESCRIPTION
**Pull request by coreymbe**
Adding catalog_inputs to the pg_repack scheme for PE 2019.8.0+.

### CODE REVIEW

**Review by MartyEwings — CHANGES_REQUESTED** [review]
Would it be possible to add this table to the existing catalogs tables cron job ?

**Comment by coreymbe** [comment]
@MartyEwings :: I can, but doing so will cause the catalogs repack to fail pre 2019.8.

tail /var/log/puppetlabs/pe_databases_cron/catalogs_repack.log
ERROR: pg_repack failed with error: ERROR:  relation "catalog_inputs" does not exist

facter -p pe_server_version
2018.1.18

**Comment by MartyEwings** [comment]
> @MartyEwings :: I can, but doing so will cause the catalogs repack to fail pre 2019.8.
> 
> tail /var/log/puppetlabs/pe_databases_cron/catalogs_repack.log

That table came in in 2019.8.2 so we will have to have a conditional that exempts it prior to this release as we have to support 2019.8.x

There is a conditional nick points to as an example in the  comments of the previous PR https://github.com/puppetlabs/puppetlabs-pe_databases/pull/47

that should do the job

**Comment by coreymbe** [comment]
Ahh, I see now. Okay that makes more sense, I'll get that fixed up. 👍🏽

**Comment by MartyEwings** [comment]
tested and is working on 2021.1 as well

**Pull request merged**
